const hydraFunctions = [
    {name : "noise", params : [{name: "scale", value: 10, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "voronoi", params : [{name: "scale", value: 5, min: 0, max: 100, type: "int"}, {name: "speed", value: 0.3, min: 0, max: 1, type: "float"}, {name: "blending", value: 0.3, min: 0, max: 1, type: "float"}] },
    {name : "osc", params : [{name: "frequency", value: 60, min: 0, max: 100, type: "int"}, {name: "sync", value: 0.1, min: 0, max: 1, type: "float"}, {name: "offset", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "shape", params : [{name: "sides", value: 3, min: 0, max: 100, type: "int"}, {name: "radius", value: 0.3, min: 0, max: 1, type: "float"}, {name: "smoothing", value: 0.01, min: 0, max: 1, type: "float"}] },
    {name : "gradient", params : [{name: "speed", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "src", params : [{name: "texture", value: null, min: null, max: null, type: "string"}] },
    {name : "solid", params : [{name: "r", value: 1, min: 0, max: 1, type: "float"}, {name: "g", value: 1, min: 0, max: 1, type: "float"}, {name: "b", value: 1, min: 0, max: 1, type: "float"}, {name: "a", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "rotate", params : [{name: "angle", value: 0.1, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scale", params : [{name: "amount", value: 1.5, min: 0, max: 100, type: "float"}, {name: "xMult", value: 1, min: 0, max: 100, type: "float"}, {name: "yMult", value: 1, min: 0, max: 100, type: "float"}] },
    {name : "pixelate", params : [{name: "x", value: 10, min: 0, max: 100, type: "int"}, {name: "y", value: 10, min: 0, max: 100, type: "int"}] },
    {name : "repeat", params : [{name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offsetX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "offsetY", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "repeatX", params : [{name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "repeatY", params : [{name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "kaleid", params : [{name: "nSides", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "scroll", params : [{name: "x", value: 0.5, min: 0, max: 1, type: "float"}, {name: "y", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speedX", value: 0, min: 0, max: 1, type: "float"}, {name: "speedY", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scrollX", params : [{name: "x", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scrollY", params : [{name: "y", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "posterize", params : [{name: "bins", value: 3, min: 0, max: 100, type: "int"}, {name: "gamma", value: 0.6, min: 0, max: 1, type: "float"}] },
    {name : "shift", params : [{name: "r", value: 0.5, min: 0, max: 1, type: "float"}, {name: "g", value: 0.5, min: 0, max: 1, type: "float"}, {name: "b", value: 0.5, min: 0, max: 1, type: "float"}, {name: "a", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "invert", params : [{name: "amount", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "contrast", params : [{name: "amount", value: 1.6, min: 0, max: 100, type: "float"}] },
    {name : "brightness", params : [{name: "amount", value: 0.4, min: 0, max: 1, type: "float"}] },
    {name : "luma", params : [{name: "threshold", value: 0.5, min: 0, max: 1, type: "float"}, {name: "tolerance", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "thresh", params : [{name: "threshold", value: 0.5, min: 0, max: 1, type: "float"}, {name: "tolerance", value: 0.04, min: 0, max: 1, type: "float"}] },
    {name : "color", params : [{name: "r", value: 1, min: 0, max: 1, type: "float"}, {name: "g", value: 1, min: 0, max: 1, type: "float"}, {name: "b", value: 1, min: 0, max: 1, type: "float"}, {name: "a", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "saturate", params : [{name: "amount", value: 0.9, min: 0, max: 1, type: "float"}] },
    {name : "hue", params : [{name: "amount", value: 0.4, min: 0, max: 1, type: "float"}] },
    {name : "colorama", params : [{name: "amount", value: 0.005, min: 0, max: 1, type: "float"}] },
    {name : "sum", params : [{name: "texture", value: null, min: null, max: null, type: "string"}] },
    {name : "r", params : [] },
    {name : "g", params : [] },
    {name : "b", params : [] },
    {name : "a", params : [] },
    {name : "add", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "sub", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "layer", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "blend", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "mult", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "diff", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "mask", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "alpha", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeat", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offsetX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "offsetY", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeatX", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeatY", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateKaleid", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "nSides", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "modulateScrollX", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "scrollX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulateScrollY", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "scrollY", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateScale", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "multiple", value: 1.5, min: 0, max: 100, type: "float"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulatePixelate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 10, min: 0, max: 100, type: "int"}, {name: "y", value: 10, min: 0, max: 100, type: "int"}] },
    {name : "modulateRotate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "angle", value: 0.1, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulateHue", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "initCam", params : [] },
    {name : "initImage", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "initVideo", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "init", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "initStream", params : [{name: "stream", value: null, min: null, max: null, type: "string"}] },
    {name : "initScreen", params : [] },
    {name : "render", params : [] },
    {name : "update", params : [] },
    {name : "setResolution", params : [{name: "width", value: 1280, min: 0, max: 10000, type: "int"}, {name: "height", value: 720, min: 0, max: 10000, type: "int"}] },
    {name : "hush", params : [] },
    {name : "setFunction", params : [{name: "name", value: "", min: null, max: null, type: "string"}, {name: "function", value: null, min: null, max: null, type: "string"}] },
    {name : "speed", params : [{name: "speed", value: 1, min: 0, max: 100, type: "int"}] },
    {name : "bpm", params : [{name: "bpm", value: 60, min: 0, max: 300, type: "int"}] },
    {name : "width", params : [{name: "width", value: 1280, min: 0, max: 10000, type: "int"}] },
    {name : "height", params : [{name: "height", value: 720, min: 0, max: 10000, type: "int"}] },
    {name : "time", params : [] },
    {name : "mouse", params : [] },
    {name : "fast", params : [] },
    {name : "smooth", params : [] },
    {name : "ease", params : [] },
    {name : "offset", params : [] },
    {name : "fit", params : [] },
    {name : "fft", params : [] },
    {name : "setSmooth", params : [{name: "amount", value: 0.8, min: 0, max: 1, type: "float"}] },
    {name : "setCutoff", params : [{name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "setBins", params : [{name: "bins", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "setScale", params : [{name: "scale", value: 1, min: 0, max: 100, type: "int"}] },
    {name : "hide", params : [] },
    {name : "show", params : [] },
    {name : "Math.sin", params : [{name: "angle", value: 0.5, min: 0, max: 1, type: "float"}] }
];

// All Functions, for reference:
/*
const hydraFunctions = [
    {name : "noise", params : [{name: "scale", value: 10, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "voronoi", params : [{name: "scale", value: 5, min: 0, max: 100, type: "int"}, {name: "speed", value: 0.3, min: 0, max: 1, type: "float"}, {name: "blending", value: 0.3, min: 0, max: 1, type: "float"}] },
    {name : "osc", params : [{name: "frequency", value: 60, min: 0, max: 100, type: "int"}, {name: "sync", value: 0.1, min: 0, max: 1, type: "float"}, {name: "offset", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "shape", params : [{name: "sides", value: 3, min: 0, max: 100, type: "int"}, {name: "radius", value: 0.3, min: 0, max: 1, type: "float"}, {name: "smoothing", value: 0.01, min: 0, max: 1, type: "float"}] },
    {name : "gradient", params : [{name: "speed", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "src", params : [{name: "texture", value: null, min: null, max: null, type: "string"}] },
    {name : "solid", params : [{name: "r", value: 1, min: 0, max: 1, type: "float"}, {name: "g", value: 1, min: 0, max: 1, type: "float"}, {name: "b", value: 1, min: 0, max: 1, type: "float"}, {name: "a", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "rotate", params : [{name: "angle", value: 0.1, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scale", params : [{name: "amount", value: 1.5, min: 0, max: 100, type: "float"}, {name: "xMult", value: 1, min: 0, max: 100, type: "float"}, {name: "yMult", value: 1, min: 0, max: 100, type: "float"}] },
    {name : "pixelate", params : [{name: "x", value: 10, min: 0, max: 100, type: "int"}, {name: "y", value: 10, min: 0, max: 100, type: "int"}] },
    {name : "repeat", params : [{name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offsetX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "offsetY", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "repeatX", params : [{name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "repeatY", params : [{name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "kaleid", params : [{name: "nSides", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "scroll", params : [{name: "x", value: 0.5, min: 0, max: 1, type: "float"}, {name: "y", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speedX", value: 0, min: 0, max: 1, type: "float"}, {name: "speedY", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scrollX", params : [{name: "x", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "scrollY", params : [{name: "y", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "posterize", params : [{name: "bins", value: 3, min: 0, max: 100, type: "int"}, {name: "gamma", value: 0.6, min: 0, max: 1, type: "float"}] },
    {name : "shift", params : [{name: "r", value: 0.5, min: 0, max: 1, type: "float"}, {name: "g", value: 0.5, min: 0, max: 1, type: "float"}, {name: "b", value: 0.5, min: 0, max: 1, type: "float"}, {name: "a", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "invert", params : [{name: "amount", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "contrast", params : [{name: "amount", value: 1.6, min: 0, max: 100, type: "float"}] },
    {name : "brightness", params : [{name: "amount", value: 0.4, min: 0, max: 1, type: "float"}] },
    {name : "luma", params : [{name: "threshold", value: 0.5, min: 0, max: 1, type: "float"}, {name: "tolerance", value: 0.1, min: 0, max: 1, type: "float"}] },
    {name : "thresh", params : [{name: "threshold", value: 0.5, min: 0, max: 1, type: "float"}, {name: "tolerance", value: 0.04, min: 0, max: 1, type: "float"}] },
    {name : "color", params : [{name: "r", value: 1, min: 0, max: 1, type: "float"}, {name: "g", value: 1, min: 0, max: 1, type: "float"}, {name: "b", value: 1, min: 0, max: 1, type: "float"}, {name: "a", value: 1, min: 0, max: 1, type: "float"}] },
    {name : "saturate", params : [{name: "amount", value: 0.9, min: 0, max: 1, type: "float"}] },
    {name : "hue", params : [{name: "amount", value: 0.4, min: 0, max: 1, type: "float"}] },
    {name : "colorama", params : [{name: "amount", value: 0.005, min: 0, max: 1, type: "float"}] },
    {name : "sum", params : [{name: "texture", value: null, min: null, max: null, type: "string"}] },
    {name : "r", params : [] },
    {name : "g", params : [] },
    {name : "b", params : [] },
    {name : "a", params : [] },
    {name : "add", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "sub", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "layer", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "blend", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "mult", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "diff", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "mask", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "alpha", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeat", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offsetX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "offsetY", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeatX", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateRepeatY", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "y", value: 3, min: 0, max: 100, type: "int"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateKaleid", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "nSides", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "modulateScrollX", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "scrollX", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulateScrollY", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "scrollY", value: 0.5, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulateScale", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "multiple", value: 1.5, min: 0, max: 100, type: "float"}, {name: "offset", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "modulatePixelate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "x", value: 10, min: 0, max: 100, type: "int"}, {name: "y", value: 10, min: 0, max: 100, type: "int"}] },
    {name : "modulateRotate", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "angle", value: 0.1, min: 0, max: 1, type: "float"}, {name: "speed", value: 0, min: 0, max: 1, type: "float"}] },
    {name : "modulateHue", params : [{name: "texture", value: null, min: null, max: null, type: "string"}, {name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "initCam", params : [] },
    {name : "initImage", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "initVideo", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "init", params : [{name: "url", value: "", min: null, max: null, type: "string"}] },
    {name : "initStream", params : [{name: "stream", value: null, min: null, max: null, type: "string"}] },
    {name : "initScreen", params : [] },
    {name : "render", params : [] },
    {name : "update", params : [] },
    {name : "setResolution", params : [{name: "width", value: 1280, min: 0, max: 10000, type: "int"}, {name: "height", value: 720, min: 0, max: 10000, type: "int"}] },
    {name : "hush", params : [] },
    {name : "setFunction", params : [{name: "name", value: "", min: null, max: null, type: "string"}, {name: "function", value: null, min: null, max: null, type: "string"}] },
    {name : "speed", params : [{name: "speed", value: 1, min: 0, max: 100, type: "int"}] },
    {name : "bpm", params : [{name: "bpm", value: 60, min: 0, max: 300, type: "int"}] },
    {name : "width", params : [{name: "width", value: 1280, min: 0, max: 10000, type: "int"}] },
    {name : "height", params : [{name: "height", value: 720, min: 0, max: 10000, type: "int"}] },
    {name : "time", params : [] },
    {name : "mouse", params : [] },
    {name : "fast", params : [] },
    {name : "smooth", params : [] },
    {name : "ease", params : [] },
    {name : "offset", params : [] },
    {name : "fit", params : [] },
    {name : "fft", params : [] },
    {name : "setSmooth", params : [{name: "amount", value: 0.8, min: 0, max: 1, type: "float"}] },
    {name : "setCutoff", params : [{name: "amount", value: 0.5, min: 0, max: 1, type: "float"}] },
    {name : "setBins", params : [{name: "bins", value: 4, min: 0, max: 100, type: "int"}] },
    {name : "setScale", params : [{name: "scale", value: 1, min: 0, max: 100, type: "int"}] },
    {name : "hide", params : [] },
    {name : "show", params : [] },
    {name : "Math.sin", params : [{name: "angle", value: 0.5, min: 0, max: 1, type: "float"}] }
];

*/