const hydraFunctions = [
    {name : "noise", params : {"scale": 10, "offset": 0.1} },
    {name : "voronoi", params : {"scale": 5, "speed": 0.3, "blending": 0.3} },
    {name : "osc", params : {"frequency": 60, "sync": 0.1, "offset": 0.1} },
    {name : "shape", params : {"sides": 3, "radius": 0.3, "smoothing": 0.01} },
    {name : "gradient", params : {"speed": 0.1} },
    {name : "src", params : {"texture": null} },
    {name : "solid", params : {"r": 1, "g": 1, "b": 1, "a": 1} },
    {name : "rotate", params : {"angle": 0.1, "speed": 0} },
    {name : "scale", params : {"amount": 1.5, "xMult": 1, "yMult": 1} },
    {name : "pixelate", params : {"x": 10, "y": 10} },
    {name : "repeat", params : {"x": 3, "y": 3, "offsetX": 0.5, "offsetY": 0.5} },
    {name : "repeatX", params : {"x": 3, "offset": 0.5} },
    {name : "repeatY", params : {"y": 3, "offset": 0.5} },
    {name : "kaleid", params : {"nSides": 4} },
    {name : "scroll", params : {"x": 0.5, "y": 0.5, "speedX": 0, "speedY": 0} },
    {name : "scrollX", params : {"x": 0.5, "speed": 0} },
    {name : "scrollY", params : {"y": 0.5, "speed": 0} },
    {name : "posterize", params : {"bins": 3, "gamma": 0.6} },
    {name : "shift", params : {"r": 0.5, "g": 0.5, "b": 0.5, "a": 0.5} },
    {name : "invert", params : {"amount": 1} },
    {name : "contrast", params : {"amount": 1.6} },
    {name : "brightness", params : {"amount": 0.4} },
    {name : "luma", params : {"threshold": 0.5, "tolerance": 0.1} },
    {name : "thresh", params : {"threshold": 0.5, "tolerance": 0.04} },
    {name : "color", params : {"r": 1, "g": 1, "b": 1, "a": 1} },
    {name : "saturate", params : {"amount": 0.9} },
    {name : "hue", params : {"amount": 0.4} },
    {name : "colorama", params : {"amount": 0.005} },
    {name : "sum", params : {"texture": null} },
    {name : "r", params : {} },
    {name : "g", params : {} },
    {name : "b", params : {} },
    {name : "a", params : {} },
    {name : "add", params : {"texture": null, "amount": 0.5} },
    {name : "sub", params : {"texture": null, "amount": 0.5} },
    {name : "layer", params : {"texture": null, "amount": 0.5} },
    {name : "blend", params : {"texture": null, "amount": 0.5} },
    {name : "mult", params : {"texture": null, "amount": 0.5} },
    {name : "diff", params : {"texture": null, "amount": 0.5} },
    {name : "mask", params : {"texture": null, "alpha": 0.5} },
    {name : "modulateRepeat", params : {"texture": null, "x": 3, "y": 3, "offsetX": 0.5, "offsetY": 0.5} },
    {name : "modulateRepeatX", params : {"texture": null, "x": 3, "offset": 0.5} },
    {name : "modulateRepeatY", params : {"texture": null, "y": 3, "offset": 0.5} },
    {name : "modulateKaleid", params : {"texture": null, "nSides": 4} },
    {name : "modulateScrollX", params : {"texture": null, "scrollX": 0.5, "speed": 0} },
    {name : "modulateScrollY", params : {"texture": null, "scrollY": 0.5, "speed": 0} },
    {name : "modulate", params : {"texture": null, "amount": 0.5} },
    {name : "modulateScale", params : {"texture": null, "multiple": 1.5, "offset": 0.5} },
    {name : "modulatePixelate", params : {"texture": null, "x": 10, "y": 10} },
    {name : "modulateRotate", params : {"texture": null, "angle": 0.1, "speed": 0} },
    {name : "modulateHue", params : {"texture": null, "amount": 0.5} },
    {name : "initCam", params : {} },
    {name : "initImage", params : {"url": ""} },
    {name : "initVideo", params : {"url": ""} },
    {name : "init", params : {"url": ""} },
    {name : "initStream", params : {"stream": null} },
    {name : "initScreen", params : {} },
    {name : "render", params : {} },
    {name : "update", params : {} },
    {name : "setResolution", params : {"width": 1280, "height": 720} },
    {name : "hush", params : {} },
    {name : "setFunction", params : {name: "", "function": null} },
    {name : "speed", params : {"speed": 1} },
    {name : "bpm", params : {"bpm": 60} },
    {name : "width", params : {"width": 1280} },
    {name : "height", params : {"height": 720} },
    {name : "time", params : {} },
    {name : "mouse", params : {} },
    {name : "fast", params : {} },
    {name : "smooth", params : {} },
    {name : "ease", params : {} },
    {name : "offset", params : {} },
    {name : "fit", params : {} },
    {name : "fft", params : {} },
    {name : "setSmooth", params : {"amount": 0.8} },
    {name : "setCutoff", params : {"amount": 0.5} },
    {name : "setBins", params : {"bins": 4} },
    {name : "setScale", params : {"scale": 1} },
    {name : "hide", params : {} },
    {name : "show", params : {} },
    {name : "Math.sin", params : {"angle" : 0.5} }
];

// All Functions, for reference:
/*
const hydraFunctions = [
    {name : "noise", params : {"scale": 10, "offset": 0.1} },
    {name : "voronoi", params : {"scale": 5, "speed": 0.3, "blending": 0.3} },
    {name : "osc", params : {"frequency": 60, "sync": 0.1, "offset": 0.1} },
    {name : "shape", params : {"sides": 3, "radius": 0.3, "smoothing": 0.01} },
    {name : "gradient", params : {"speed": 0.1} },
    {name : "src", params : {"texture": null} },
    {name : "solid", params : {"r": 1, "g": 1, "b": 1, "a": 1} },
    {name : "rotate", params : {"angle": 0.1, "speed": 0} },
    {name : "scale", params : {"amount": 1.5, "xMult": 1, "yMult": 1} },
    {name : "pixelate", params : {"x": 10, "y": 10} },
    {name : "repeat", params : {"x": 3, "y": 3, "offsetX": 0.5, "offsetY": 0.5} },
    {name : "repeatX", params : {"x": 3, "offset": 0.5} },
    {name : "repeatY", params : {"y": 3, "offset": 0.5} },
    {name : "kaleid", params : {"nSides": 4} },
    {name : "scroll", params : {"x": 0.5, "y": 0.5, "speedX": 0, "speedY": 0} },
    {name : "scrollX", params : {"x": 0.5, "speed": 0} },
    {name : "scrollY", params : {"y": 0.5, "speed": 0} },
    {name : "posterize", params : {"bins": 3, "gamma": 0.6} },
    {name : "shift", params : {"r": 0.5, "g": 0.5, "b": 0.5, "a": 0.5} },
    {name : "invert", params : {"amount": 1} },
    {name : "contrast", params : {"amount": 1.6} },
    {name : "brightness", params : {"amount": 0.4} },
    {name : "luma", params : {"threshold": 0.5, "tolerance": 0.1} },
    {name : "thresh", params : {"threshold": 0.5, "tolerance": 0.04} },
    {name : "color", params : {"r": 1, "g": 1, "b": 1, "a": 1} },
    {name : "saturate", params : {"amount": 0.9} },
    {name : "hue", params : {"amount": 0.4} },
    {name : "colorama", params : {"amount": 0.005} },
    {name : "sum", params : {"texture": null} },
    {name : "r", params : {} },
    {name : "g", params : {} },
    {name : "b", params : {} },
    {name : "a", params : {} },
    {name : "add", params : {"texture": null, "amount": 0.5} },
    {name : "sub", params : {"texture": null, "amount": 0.5} },
    {name : "layer", params : {"texture": null, "amount": 0.5} },
    {name : "blend", params : {"texture": null, "amount": 0.5} },
    {name : "mult", params : {"texture": null, "amount": 0.5} },
    {name : "diff", params : {"texture": null, "amount": 0.5} },
    {name : "mask", params : {"texture": null, "alpha": 0.5} },
    {name : "modulateRepeat", params : {"texture": null, "x": 3, "y": 3, "offsetX": 0.5, "offsetY": 0.5} },
    {name : "modulateRepeatX", params : {"texture": null, "x": 3, "offset": 0.5} },
    {name : "modulateRepeatY", params : {"texture": null, "y": 3, "offset": 0.5} },
    {name : "modulateKaleid", params : {"texture": null, "nSides": 4} },
    {name : "modulateScrollX", params : {"texture": null, "scrollX": 0.5, "speed": 0} },
    {name : "modulateScrollY", params : {"texture": null, "scrollY": 0.5, "speed": 0} },
    {name : "modulate", params : {"texture": null, "amount": 0.5} },
    {name : "modulateScale", params : {"texture": null, "multiple": 1.5, "offset": 0.5} },
    {name : "modulatePixelate", params : {"texture": null, "x": 10, "y": 10} },
    {name : "modulateRotate", params : {"texture": null, "angle": 0.1, "speed": 0} },
    {name : "modulateHue", params : {"texture": null, "amount": 0.5} },
    {name : "initCam", params : {} },
    {name : "initImage", params : {"url": ""} },
    {name : "initVideo", params : {"url": ""} },
    {name : "init", params : {"url": ""} },
    {name : "initStream", params : {"stream": null} },
    {name : "initScreen", params : {} },
    {name : "render", params : {} },
    {name : "update", params : {} },
    {name : "setResolution", params : {"width": 1280, "height": 720} },
    {name : "hush", params : {} },
    {name : "setFunction", params : {name: "", "function": null} },
    {name : "speed", params : {"speed": 1} },
    {name : "bpm", params : {"bpm": 60} },
    {name : "width", params : {"width": 1280} },
    {name : "height", params : {"height": 720} },
    {name : "time", params : {} },
    {name : "mouse", params : {} },
    {name : "fast", params : {} },
    {name : "smooth", params : {} },
    {name : "ease", params : {} },
    {name : "offset", params : {} },
    {name : "fit", params : {} },
    {name : "fft", params : {} },
    {name : "setSmooth", params : {"amount": 0.8} },
    {name : "setCutoff", params : {"amount": 0.5} },
    {name : "setBins", params : {"bins": 4} },
    {name : "setScale", params : {"scale": 1} },
    {name : "hide", params : {} },
    {name : "show", params : {} }
];
*/